default: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: marcelo
  password: 123456

development:
  <<: *defaults
  database: ticketee_development

test: &test
  <<: *defaults
  database: ticketee_test

production:
  <<: *defaults
  database: ticketee_production
